name       : gnome-sound-recorder
version    : 3.32.1
release    : 6
source     :
    - https://download.gnome.org/sources/gnome-sound-recorder/3.32/gnome-sound-recorder-3.32.1.tar.xz : 4b405fa8a783d24657e95221c7fe6ffc6bd517dc1c705691e475b2a59a590361
license    : GPL-2.0-only
component  : multimedia.audio
summary    : Sound recorder from GNOME
description: |
    Sound recorder from GNOME
builddeps  :
    - pkgconfig(gjs-1.0)
    - pkgconfig(gstreamer-plugins-bad-1.0)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(gtk+-3.0)
    - gstreamer-1.0-plugins-good
rundeps    :
    - gjs
    - gstreamer-1.0-plugins-good
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
