name       : gnome-sound-recorder
version    : 3.20.2
release    : 1
source     :
    - https://download.gnome.org/sources/gnome-sound-recorder/3.20/gnome-sound-recorder-3.20.2.tar.xz : 25b2b452cb59851205164426a942121964f0bf49091c3789fb6bce9b9c6de3f2
license    : GPL-2.0
component  : multimedia.audio
summary    : Sound recorder from GNOME
description: |
    Sound recorder from GNOME
builddeps  :
    - pkgconfig(gjs-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gstreamer-1.0)
    - gnome-common
rundeps    :
    - gjs
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
