name       : gnome-sound-recorder
version    : 3.24.0
release    : 2
source     :
    - https://download.gnome.org/sources/gnome-sound-recorder/3.24/gnome-sound-recorder-3.24.0.tar.xz : f5d06c4d1eb7e41024c71e9bfafcca3d7f96ce5c3eab56caa4845a40432c8954
license    : GPL-2.0
component  : multimedia.audio
summary    : Sound recorder from GNOME
description: |
    Sound recorder from GNOME
builddeps  :
    - pkgconfig(gjs-1.0)
    - pkgconfig(gstreamer-bad-base-1.0)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(gtk+-3.0)
    - gnome-common
    - gstreamer-1.0-plugins-good
rundeps    :
    - gjs
    - gstreamer-1.0-plugins-good
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
