name       : gnome-sound-recorder
version    : 3.34.0
release    : 7
source     :
    - https://download.gnome.org/sources/gnome-sound-recorder/3.34/gnome-sound-recorder-3.34.0.tar.xz : 49f1d6e0c06ac3bacc6084b2f5a63c8b91c5a20c3fc824532b7736a1151684c4
license    : GPL-2.0-only
component  : multimedia.audio
summary    : Sound recorder from GNOME
description: |
    Sound recorder from GNOME
builddeps  :
    - pkgconfig(gjs-1.0)
    - pkgconfig(gstreamer-plugins-bad-1.0)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(gtk+-3.0)
    - gstreamer-1.0-plugins-good
rundeps    :
    - gjs
    - gstreamer-1.0-plugins-good
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
