name       : gnome-sound-recorder
version    : 3.32.0
release    : 5
source     :
    - https://download.gnome.org/sources/gnome-sound-recorder/3.32/gnome-sound-recorder-3.32.0.tar.xz : f7eabcc6f38927d01ca54e3a25db7db740b14b649a382607642abd5aaefa9065
license    : GPL-2.0-only
component  : multimedia.audio
summary    : Sound recorder from GNOME
description: |
    Sound recorder from GNOME
builddeps  :
    - pkgconfig(gjs-1.0)
    - pkgconfig(gstreamer-plugins-bad-1.0)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(gtk+-3.0)
    - gstreamer-1.0-plugins-good
rundeps    :
    - gjs
    - gstreamer-1.0-plugins-good
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
