name       : gnome-sound-recorder
version    : 3.28.1
release    : 4
source     :
    - https://download.gnome.org/sources/gnome-sound-recorder/3.28/gnome-sound-recorder-3.28.1.tar.xz : 1e4b67c6fae4ca084ab432a50818d39a3d5a430eb2995b86523ce40d83cc1a78
license    : GPL-2.0-only
component  : multimedia.audio
summary    : Sound recorder from GNOME
description: |
    Sound recorder from GNOME
builddeps  :
    - pkgconfig(gjs-1.0)
    - pkgconfig(gstreamer-plugins-bad-1.0)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(gtk+-3.0)
    - gnome-common
    - gstreamer-1.0-plugins-good
rundeps    :
    - gjs
    - gstreamer-1.0-plugins-good
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
